version: "3.8"

services:
  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - hardhat_cache:/app/cache
      - hardhat_artifacts:/app/artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s
    environment:
      - HARDHAT_NETWORK=hardhat
      - HARDHAT_CHAIN_ID=1337

  api1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - API_DEPLOYER=true
      - HARDHAT_URL=http://hardhat:8545
      - DEPLOYMENT_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - DEPLOYMENT_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - NETWORK_ID=1337
      - GAS_LIMIT=2000000
    depends_on:
      hardhat:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Aguardando Hardhat estar pronto...' &&
        while ! curl -s http://hardhat:8545 > /dev/null; do
          echo 'Aguardando Hardhat...'
          sleep 10
        done &&
        echo 'Hardhat está pronto!' &&
        sleep 15 &&
        python app/main.py
      "
    volumes:
      - shared_app:/app

  api2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - API_DEPLOYER=false
      - HARDHAT_URL=http://hardhat:8545
      - DEPLOYMENT_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - DEPLOYMENT_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - NETWORK_ID=1337
      - GAS_LIMIT=2000000
    depends_on:
      hardhat:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Aguardando Hardhat estar pronto...' &&
        while ! curl -s http://hardhat:8545 > /dev/null; do
          echo 'Aguardando Hardhat...'
          sleep 10
        done &&
        echo 'Hardhat está pronto!' &&
        sleep 15 &&
        python app/main.py
      "
    volumes:
      - shared_app:/app

  api3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - API_DEPLOYER=false
      - HARDHAT_URL=http://hardhat:8545
      - DEPLOYMENT_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - DEPLOYMENT_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - NETWORK_ID=1337
      - GAS_LIMIT=2000000
    depends_on:
      hardhat:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Aguardando Hardhat estar pronto...' &&
        while ! curl -s http://hardhat:8545 > /dev/null; do
          echo 'Aguardando Hardhat...'
          sleep 10
        done &&
        echo 'Hardhat está pronto!' &&
        sleep 15 &&
        python app/main.py
      "
    volumes:
      - shared_app:/app

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3

volumes:
  hardhat_cache:
  hardhat_artifacts:
  shared_app:

networks:
  default:
    name: blockchain-network
    driver: bridge
